name: unittest

on:
  push:
    paths:
      - '*.py'

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.12
          architecture: x64
      - name: Checkout math_puzzle
        uses: actions/checkout@master
      - name: get python version
        run: python -V
      - name: unittest for python
        run: python -m unittest discover tests -v
